// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "BFL_CreateBP.generated.h"

/**
 * 
 */
UCLASS()
class FBXIMPORTERUTILPLUGIN_API UBFL_CreateBP : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "FBX Parser|Editor", meta = (DevelopmentOnly))
	static void GenerateTarBlueprint(const FString& FBXPath, const FString& AssetPath, UStaticMesh* TarMesh, UMaterialInterface* TarMaterial);	
	
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "FBX Parser|Editor", meta = (DevelopmentOnly))
	static void GenerateRunWay15LightBlueprint(const FString& FBXPath, const FString& AssetPath, UStaticMesh* TarMesh, UMaterialInterface* TarMaterial);

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "FBX Parser|Editor", meta = (DevelopmentOnly))
	static void GenerateRunWay15LightModelBlueprint(const FString& FBXPath, const FString& AssetPath, UMaterialInterface* TarMaterial);

	/**
	 * @param AssetPath 资产路径，例如 "/Game/AutoGenerated/BP_Planes"
	 * @param CenterPoints 平面中心点数组（世界坐标或局部坐标均可）
	 * @param TarMesh   使用的静态网格
	 * @return 创建的蓝图指针，失败时为 nullptr
	 */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "FBX Parser|Editor", meta = (DevelopmentOnly))
	static UBlueprint* CreateTarBlueprint(const FString& AssetPath, const TArray<FVector>& CenterPoints, UStaticMesh* TarMesh, UMaterialInterface* TarMaterial);

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "FBX Parser|Editor", meta = (DevelopmentOnly))
	static UBlueprint* CreateTarModelBlueprint(const FString& AssetPath, const TArray<FVector>& CenterPoints, UMaterialInterface* TarMaterial);
};
