// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "BFL_CreateBP.generated.h"

/**
 * 
 */
UCLASS()
class FBXIMPORTERUTILPLUGIN_API UBFL_CreateBP : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

	//// 用来生成 Plane 的 Mesh
	//UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FBX Parser")
	//UStaticMesh* PlaneMesh;

	//// 生成蓝图的目标路径
	//UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FBX Parser")
	//FString AssetPath = TEXT("/Game/AutoGenerated/BP_PlanesFromActor");

	//// 在编辑器里显示成一个按钮
	//UFUNCTION(CallInEditor, Category = "FBX Parser|Editor")

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "FBX Parser|Editor", meta = (DevelopmentOnly))
	static void GeneratePlanesBlueprint(const FString& FBXPath, const FString& AssetPath, UStaticMesh* PlaneMesh);

	/**
	 * @param AssetPath 资产路径，例如 "/Game/AutoGenerated/BP_Planes"
	 * @param CenterPoints 平面中心点数组（世界坐标或局部坐标均可）
	 * @param PlaneMesh   使用的 Plane 静态网格
	 * @return 创建的蓝图指针，失败时为 nullptr
	 */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "FBX Parser|Editor", meta = (DevelopmentOnly))
	static UBlueprint* CreatePlanesBlueprint(
		const FString& AssetPath,
		const TArray<FVector>& CenterPoints,
		UStaticMesh* PlaneMesh
	);
};
